### ISSUE TITLE
Ужаснейший код.

### ISSUE THREAD

**Issue by kravetsone** [IDMLP/Meow-LP-LP-Iris-CM#6]

**Comment by spelsinx** [comment]
да, говнокод, как и у тебя

**Comment by kravetsone** [comment]
> да, говнокод, как и у тебя

Так меня

**Comment by alexglushich** [comment]
> да, говнокод, как и у тебя

унизил

**Comment by alexglushich** [comment]
> > да, говнокод, как и у тебя
> 
> Так меня

я посмотрел код, подари новые глаза пожалуйста

**Comment by spelsinx** [comment]
сорь есль обидель
